### ISSUE TITLE
No "1366 x 768" display setting

### ISSUE THREAD

**Issue by jirat-sumitanun** [IllusionMods/IllusionLaunchers#20]
I played RX11 for a long time and now I just update to. RX19.
RX11 can setting "1366 x 768" display. IllusionLaunchers in RX11 is version IllusionLaunchers_Koikatsu_3.3.2.0
I have see your code
In src/SharedSettingsNew/SettingManagerNew.cs
Row 65,66 width and height value are wrong.
In src/SharedSettingsOld/SettingManagerOld.cs
You didn't include "1366 x 768" 

it look like you remove "1366 x 768" in this commit f89f61e9cb941c658147e9609ae2068f1692a3da

**Comment by Maxitox** [comment]
I have the exact same issue, which started happening since I updated my Koikatsu BP to RX18, 19 or 20 (I don't really remember which exact version). 

My launcher's resolution settings are capped up to 1280 x 720, no matter if I have it in window mode or full-screen mode, not even editing the settings on the .xml file seems to work.
![image](https://github.com/IllusionMods/IllusionLaunchers/assets/99861111/c2f055ef-9b6b-447f-a594-48a8c98dca09)

The only workarounds I could find is to either manually change the resolution in-game on the Plugin Options menu (with the downside of having to do this everytime you launch the game), or downgrade the IllusionLauncher back to v3.3.0, which still has the 1366 x 768 option available.
